AllCops:
  NewCops: enable
  SuggestExtensions: true

require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-magic_numbers

MagicNumbers/NoArgument:
  Enabled: true

MagicNumbers/NoAssignment:
  Enabled: true

MagicNumbers/NoDefault:
  Enabled: true

MagicNumbers/NoReturn:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb
