AllCops:
  NewCops: enable
  SuggestExtensions: true

require:
  - rubocop-rake
  - rubocop-minitest
  - ./lib/rubocop/no_magic_numbers.rb

MagicNumbers/NoArgument:
  Enabled: true

MagicNumbers/NoAssignment:
  Enabled: true

MagicNumbers/NoReturn:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb
