AllCops:
  NewCops: enable
  SuggestExtensions: true

require:
  - rubocop-rake
  - rubocop-minitest
  - ./lib/rubocop/cop/magic_numbers/no_magic_numbers.rb

MagicNumbers/NoMagicNumbers:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb
